#FROM thinkr/rfull
FROM jrnold/rstan

RUN apt-get update 
RUN apt-get install -y libgdal-dev gdal-bin
RUN apt-get install -y libgsl0-dev
RUN apt-get install -y libudunits2-dev

#RUN R -e "remotes::update_packages('dplyr', dependencies = TRUE)"
RUN R -e "utils::install.packages(c('leaflet','rgdal','raster','shiny','parallel','rstan','knitr','inlmisc','shinycssloaders','DT','RandomFields','stringr','devtools','rmarkdown','rlist','digest','shinythemes' ), dependencies = TRUE)"

RUN R -e "devtools::install_github('ppernot/FitOCTlib')"
COPY FitOCTdock_*.tar.gz  /FitOCTdock.tar.gz
RUN R -e "install.packages('FitOCTdock.tar.gz', repos = NULL, type = 'source')"

COPY Rprofile.site /usr/local/lib/R/etc
EXPOSE 3838
CMD ["R", "-e FitOCTdock::fitOCT()"]

